#
# Makefile for BM and QoS drivers.
#

# initial small drivers
#obj-$(CONFIG_LTQ_PPV4) += bm_drv_slim.o
obj-$(CONFIG_LTQ_PPV4_BM_SLIM) += bm_drv_slim.o
obj-$(CONFIG_LTQ_PPV4_QOS_SLIM) += qos_drv_slim.o

# full drivers
obj-$(CONFIG_LTQ_PPV4_QOS) += qos/
#obj-$(CONFIG_LTQ_PPV4) += bm/
obj-$(CONFIG_LTQ_PPV4_BM) += bm/
